[package]
name = "parse-derive"
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"
authors = ["Axel Lord"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = "2.0.15"
