[package]
name = "barse"
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"
authors = ["Axel Lord"]
repository = "https://github.com/axel-lord/barse"
categories = ["parsing"]
keywords = ["binary"]

[features]
derive = ["dep:barse-derive"]

[dependencies]
bytesize = "1.2.0"
barse-derive = { git = "https://github.com/axel-lord/barse-derive", optional = true }
thiserror = "1.0.40"
