[package]
name = "parse-common"
version = "0.1.0"
edition = "2021"

[features]
derive = ["dep:parse-derive"]

[dependencies]
bytesize = "1.2.0"
parse-derive = { path = "../parse-derive", optional = true }
thiserror = "1.0.40"
